### ISSUE TITLE
How do you support routing?

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [sbilly/joli-admin#1]
Hi, 

does this template also supports routing and SPA? 

looking at the demo code I see each demo page has an entire HTML document, which mean a full page reload. 

did you use some generator, or did you copy paste snippets between pages? 

for example, I can see the sidebar snippet appears on every page. I doubt you copy-pasted it to all demo pages. can you please elaborate what was your process?

**Comment by sbilly** [comment]
It's just for my personal cache. You can find the author at http://themifycloud.com/downloads/freee-responsive-bootstrap-joli-angular-js-admin-template-dashboard-web-app/
