### ISSUE TITLE
cant scroll page when modal show

### ISSUE THREAD

**Issue by ihsandwn** [sbilly/joli-admin#5]
why scroll disable when modal show? joli not support modal? thanks for help.

![capture](https://cloud.githubusercontent.com/assets/9513426/21445937/c69aab0e-c8f2-11e6-8a1f-f03a937c1a14.JPG)

**Comment by sbilly** [comment]
I just forked from http://themifycloud.com/downloads/freee-responsive-bootstrap-joli-angular-js-admin-template-dashboard-web-app/.

You can contact the original author for help.
