### ISSUE TITLE
Internacionalization

### ISSUE THREAD

**Issue by rafaellarrosa** [sbilly/joli-admin#6]
Hi @sbilly , thank you for this work, it is perfect!
I am developing web app in brazilian pt-br language, but im not found an documentation about internacionalization, can you help-me?.

thanks

**Comment by sbilly** [comment]
I forked from http://themifycloud.com/downloads/freee-responsive-bootstrap-joli-angular-js-admin-template-dashboard-web-app/. You can contact the original author for help.

I think there is no i18n support for this templates.
